name: 'oracle_lineage'
version: '1.0.0'
config-version: 2

profile: 'oracle_lineage'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  oracle_lineage:
    +materialized: view
